//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("SmartAdmin.Seed")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.9.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.9.0-dev")]
[assembly: System.Reflection.AssemblyProductAttribute("SmartAdmin for .NET Core 2.0")]
[assembly: System.Reflection.AssemblyTitleAttribute("SmartAdmin.Seed")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.9.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

